## 🗂️ 배열 속성 정보

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [3]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr3 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]],
                 [[19, 20, 21],
                  [22, 23, 24],
                  [25, 26, 27]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [5]:
def ndarray_info(arr):
    print("ndim : ", arr.ndim)
    print("shape : ", arr.shape)
    print("dtype : ", arr.dtype)
    print("size : ", arr.size)
    print("itemsize : ", arr.itemsize)
    print("nbytes : ", arr.nbytes)
    print("strides : ", arr.strides)

In [6]:
ndarray_info(arr1)

ndim :  1
shape :  (3,)
dtype :  int32
size :  3
itemsize :  4
nbytes :  12
strides :  (4,)


In [7]:
ndarray_info(arr2)

ndim :  2
shape :  (3, 3)
dtype :  int32
size :  9
itemsize :  4
nbytes :  36
strides :  (12, 4)


In [8]:
ndarray_info(arr3)

ndim :  3
shape :  (3, 3, 3)
dtype :  int32
size :  27
itemsize :  4
nbytes :  108
strides :  (36, 12, 4)


## 🗂️ 배열 조회

#### 📌 인덱싱(Indexing)

In [9]:
print(arr1)

[1 2 3]


In [10]:
print(arr1[0])
print(arr1[2])
print(arr1[-1])

1
3
3


In [11]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(arr2[0])
print(arr2[1][1])
print(arr2[2, 2])

[1 2 3]
5
9


#### 📌 슬라이싱(Slicing)

In [13]:
print(arr1)

[1 2 3]


In [14]:
print(arr1[0:2])
print(arr1[0:])
print(arr1[:1])
print(arr1[::-1])

[1 2]
[1 2 3]
[1]
[3 2 1]


In [15]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(arr2[1])
print(arr2[1][:])
print(arr2[:2, :2])
print(arr2[1:, ::-1])
print(arr2[::-1, ::-1])

[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


#### 📌 불리언 인덱싱(Boolean Indexing)
- 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
- True 값인 인덱스의 값만 조회

In [17]:
print(arr1)

[1 2 3]


In [18]:
bi = [False, True, True]
print(arr1[bi])

[2 3]


In [19]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
bi = np.random.randint(0, 2, (3, 3), dtype = bool)
print(bi)
print(arr2[bi])

[[False  True  True]
 [False  True  True]
 [ True  True  True]]
[2 3 5 6 7 8 9]


#### 📌 팬시 인덱싱(Fancy Indexing)

In [21]:
print(arr1)

[1 2 3]


In [22]:
fi = [0, 2]
print(arr1[fi])

[1 3]


In [23]:
fi = np.array([[0, 1],
               [2, 0]])
print(arr1[fi])

[[1 2]
 [3 1]]


In [24]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
row = np.array([0, 2])
col = np.array([1, 2])
print(arr2[row, col])
print(arr2[row, :])
print(arr2[:, col])
print(arr2[row, 1])
print(arr2[2, col])
print(arr2[row, 1:])
print(arr2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


#### 📌 조건 연산자를 이용한 인덱싱

In [26]:
print(arr1[arr1 > 2])

[3]


In [27]:
print(arr2[arr2 > 2])

[3 4 5 6 7 8 9]
