## 🗂️ 배열 삽입 · 수정 · 삭제

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr3 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]],
                 [[19, 20, 21],
                  [22, 23, 24],
                  [25, 26, 27]]])

#### 📌 배열 값 삽입
- ```insert()``` : 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환 후 삽입
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [3]:
print(np.insert(arr1, 0, 10))

[10  1  2  3]


In [4]:
print(np.insert(arr1, 2, 10))

[ 1  2 10  3]


In [5]:
print(np.insert(arr2, 2, 10, axis = 0))

[[ 1  2  3]
 [ 4  5  6]
 [10 10 10]
 [ 7  8  9]]


In [6]:
print(np.insert(arr2, 2, 10, axis = 1))

[[ 1  2 10  3]
 [ 4  5 10  6]
 [ 7  8 10  9]]


In [7]:
print(np.insert(arr3, 2, 10, axis = 0))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [8]:
print(np.insert(arr3, 2, 10, axis = 1))

[[[ 1  2  3]
  [ 4  5  6]
  [10 10 10]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [10 10 10]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [10 10 10]
  [25 26 27]]]


In [9]:
print(np.insert(arr3, 2, 10, axis = 2))

[[[ 1  2 10  3]
  [ 4  5 10  6]
  [ 7  8 10  9]]

 [[10 11 10 12]
  [13 14 10 15]
  [16 17 10 18]]

 [[19 20 10 21]
  [22 23 10 24]
  [25 26 10 27]]]


#### 📌 배열 값 수정
- 배열의 인덱싱으로 접근하여 값 수정

In [10]:
print(arr1)

arr1[0] = 7
arr1[1:] = [8, 9]
print(arr1)

[1 2 3]
[7 8 9]


In [11]:
fi = np.array([0, 2])

arr1[fi] = 0
print(arr1)

arr1[fi] += 8
print(arr1)

[0 8 0]
[8 8 8]


In [12]:
print(arr2)

arr2[0, 0] = 0
arr2[1, 1] = 0
arr2[2, 2] = 0

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [13]:
arr2[0] = 1
arr2[:, 0] = 1
arr2[:, 2] = 1
arr2[2] = 1

print(arr2)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [14]:
arr2[[0, 1, 1, 2],
     [1, 0, 2, 1]] = 9

print(arr2)

[[1 9 1]
 [9 0 9]
 [1 9 1]]


#### 📌 배열 값 삭제
- ```delete()``` : 배열의 특정 위치의 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [15]:
print(arr1)

[8 8 8]


In [16]:
print(np.delete(arr1, 2))

[8 8]


In [17]:
print(arr2)

[[1 9 1]
 [9 0 9]
 [1 9 1]]


In [18]:
print(np.delete(arr2, 1, axis = 0))

[[1 9 1]
 [1 9 1]]


In [19]:
print(np.delete(arr2, 1, axis = 1))

[[1 1]
 [9 9]
 [1 1]]
