## 🗂️ 배열 추가 · 병합 · 분할

In [1]:
import numpy as np

#### 📌 배열 추가
- ```append()``` : 배열의 끝에 값 추가
- axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [2]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(10, 19).reshape(3, 3)

arr3 = np.append(arr1, arr2)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis를 0으로 지정
- shape[0]을 제외한 나머지 shape은 같아야 함

In [3]:
arr3 = np.append(arr1, arr2, axis = 0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis를 1로 지정
- shape[1]을 제외한 나머지 shape은 같아야 함

In [4]:
arr3 = np.append(arr1, arr2, axis = 1)
print(arr3)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


#### 📌 배열 병합
- ```concatenate()``` : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [5]:
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])
arr3 = np.array([7, 8, 9])

print(np.concatenate((arr1, arr2, arr3)))

[1 3 5 2 4 6 7 8 9]


In [6]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(np.concatenate((arr1, arr1), axis = 0))
print(np.concatenate((arr1, arr1), axis = 1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


- ```vstack()``` : 수직 스택(Vertical Stack)

In [7]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

- ```hstack()``` : 수평 스택(Horizontal Stack)

In [8]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- ```dstack()``` : 깊이 스택(Depth Stack)

In [9]:
np.dstack((arr1, arr2))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

- ```stack()``` : 새로운 차원으로 연결

In [10]:
np.stack((arr1, arr2))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### 📌 배열 분할
- ```split()``` : 배열 분할

In [11]:
arr = np.arange(0, 10)
arr_sub1, arr_sub2 = np.split(arr, [5])
print(arr_sub1, arr_sub2)

[0 1 2 3 4] [5 6 7 8 9]


- ```vsplit()``` : 수직 분할

In [12]:
arr = np.arange(1, 10).reshape(3, 3)
arr_sub1, arr_sub2, arr_sub3 = np.vsplit(arr, [1, 2])
print(arr_sub1)
print(arr_sub2)
print(arr_sub3)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


- ```hsplit()``` : 수평 분할

In [13]:
arr = np.arange(1, 10).reshape(3, 3)
arr_sub1, arr_sub2, arr_sub3 = np.hsplit(arr, [1, 2])
print(arr_sub1)
print(arr_sub2)
print(arr_sub3)

[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


- ```dsplit()``` : 깊이 분할

In [14]:
arr = np.arange(1, 28).reshape(3, 3, 3)
arr_sub1, arr_sub2, arr_sub3 = np.dsplit(arr, [1, 2])
print(arr)
print(arr_sub1)
print(arr_sub2)
print(arr_sub3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1]
  [ 4]
  [ 7]]

 [[10]
  [13]
  [16]]

 [[19]
  [22]
  [25]]]
[[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]

 [[20]
  [23]
  [26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]
