## 🗂️ 배열 정렬

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 10, 10)
arr2 = np.random.randint(1, 10, (3, 3))
print(arr1)
print(arr2)

[5 3 8 1 4 4 2 8 5 8]
[[7 5 3]
 [6 2 6]
 [8 4 8]]


#### 📌 sort()
- 주어진 배열을 정렬
- 원본에 반영되지 않음

In [3]:
print(np.sort(arr1))

[1 2 3 4 4 5 5 8 8 8]


In [4]:
print(np.sort(arr2))

[[3 5 7]
 [2 6 6]
 [4 8 8]]


In [5]:
print(np.sort(arr2, axis = 0)) # 행 방향(axis 0) 정렬

[[6 2 3]
 [7 4 6]
 [8 5 8]]


In [6]:
print(np.sort(arr2, axis = 1)) # 열 방향(axis 1) 정렬

[[3 5 7]
 [2 6 6]
 [4 8 8]]


In [7]:
print(np.sort(arr2, axis = None)) # 1차원 배열로 변환 후 정렬

[2 3 4 5 6 6 7 8 8]


#### 📌 argsort()
- 정렬된 원소의 기존 배열에서의 인덱스

In [8]:
print(np.argsort(arr1))

[3 6 1 4 5 0 8 2 7 9]


In [9]:
print(np.argsort(arr2))

[[2 1 0]
 [1 0 2]
 [1 0 2]]


In [10]:
print(np.argsort(arr2, axis = 0)) # 행 방향(axis 0) 정렬

[[1 1 0]
 [0 2 1]
 [2 0 2]]


In [11]:
print(np.argsort(arr2, axis = 1)) # 열 방향(axis 1) 정렬

[[2 1 0]
 [1 0 2]
 [1 0 2]]


In [12]:
print(np.argsort(arr2, axis = None)) # 1차원 배열로 변환 후 정렬

[4 2 7 1 3 5 0 6 8]


#### 📌 partition()
- 배열에서 k 개의 작은 값을 우선 배치
- 나머지 값은 임의의 순서로 채워져 있음

In [13]:
arr1 = np.random.randint(1, 10, 10)
print(arr1)
print(np.partition(arr1, 3))

[3 3 1 6 5 8 9 7 6 4]
[3 3 1 4 6 8 9 7 6 5]


In [14]:
arr2 = np.random.randint(1, 10, (5, 5))
print(arr2)
print(np.partition(arr2, 3))

[[5 8 2 5 1]
 [7 1 1 2 1]
 [6 3 3 2 3]
 [2 7 1 9 3]
 [2 4 4 9 5]]
[[1 2 5 5 8]
 [1 1 1 2 7]
 [2 3 3 3 6]
 [1 2 3 7 9]
 [2 4 4 5 9]]


In [15]:
arr2 = np.random.randint(1, 10, (5, 5))
print(arr2)
print(np.partition(arr2, 3, axis = 0))

[[9 7 2 7 4]
 [5 4 6 8 7]
 [4 1 2 8 8]
 [8 5 7 3 2]
 [3 6 2 9 9]]
[[3 5 2 3 2]
 [4 1 2 7 4]
 [5 4 2 8 7]
 [8 6 6 8 8]
 [9 7 7 9 9]]


In [16]:
arr2 = np.random.randint(1, 10, (5, 5))
print(arr2)
print(np.partition(arr2, 3, axis = 1))

[[7 6 5 1 3]
 [3 8 5 1 7]
 [4 6 9 6 6]
 [6 1 7 1 5]
 [5 2 3 2 3]]
[[1 3 5 6 7]
 [1 3 5 7 8]
 [6 4 6 6 9]
 [1 5 1 6 7]
 [2 3 2 3 5]]


#### 📌 argpartition()
- 정렬된 원소의 기존 배열에서의 인덱스

In [17]:
arr1 = np.random.randint(1, 10, 10)
print(arr1)
print(np.partition(arr1, 3))
print(np.argpartition(arr1, 3))

[2 8 8 4 6 2 1 9 1 6]
[1 1 2 2 4 6 8 9 8 6]
[8 6 5 0 3 4 1 7 2 9]


In [18]:
arr2 = np.random.randint(1, 10, (5, 5))
print(arr2)
print(np.partition(arr2, 3))
print(np.argpartition(arr2, 3))

[[4 3 3 3 2]
 [3 3 1 2 2]
 [7 5 9 7 2]
 [1 1 3 8 1]
 [8 1 3 1 5]]
[[3 2 3 3 4]
 [2 1 2 3 3]
 [5 2 7 7 9]
 [1 1 1 3 8]
 [1 3 1 5 8]]
[[3 4 2 1 0]
 [3 2 4 1 0]
 [1 4 0 3 2]
 [4 0 1 2 3]
 [3 2 1 4 0]]


In [19]:
arr2 = np.random.randint(1, 10, (5, 5))
print(arr2)
print(np.partition(arr2, 3, axis = 0))
print(np.argpartition(arr2, 3, axis = 0))

[[9 1 2 3 9]
 [8 3 2 8 4]
 [7 7 9 7 3]
 [2 4 3 2 9]
 [5 7 5 4 2]]
[[2 4 3 2 2]
 [5 1 2 3 3]
 [7 3 2 4 4]
 [8 7 5 7 9]
 [9 7 9 8 9]]
[[3 3 3 3 4]
 [4 0 0 0 2]
 [2 1 1 4 1]
 [1 2 4 2 3]
 [0 4 2 1 0]]


In [20]:
arr2 = np.random.randint(1, 10, (5, 5))
print(arr2)
print(np.partition(arr2, 3, axis = 1))
print(np.argpartition(arr2, 3, axis = 1))

[[5 5 2 2 7]
 [5 5 6 1 9]
 [8 4 9 5 3]
 [4 7 8 2 9]
 [8 1 4 4 8]]
[[2 2 5 5 7]
 [1 5 5 6 9]
 [5 3 4 8 9]
 [2 4 7 8 9]
 [4 4 1 8 8]]
[[3 2 0 1 4]
 [3 0 1 2 4]
 [3 4 1 0 2]
 [3 0 1 2 4]
 [3 2 1 0 4]]
